### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by kitzler-walli** [lsiddiquee/bmw-connected-drive#11]
I just tried to use the library but receive an error at the authentication:

```
2: Getting vehicles
0: Request: https://b2vapi.bmwgroup.com/webapi/v1/user/vehicles, Method: GET, Headers: {"accept":"application/json","Content-Type":"application/json;charset=UTF-8","Authorization":"Bearer wfN9o7LoaXyDW4FDqGTL42BrjkY","x-user-agent":"android(v1.07_20200330);bmw;1.7.0(11152)"}, Body: null
0: Response: 403, Headers: {}, Body: 
Error: Error occurred while attempting 'GET' at url 'https://b2vapi.bmwgroup.com/webapi/v1/user/vehicles' with 403 body (null)
```

I checked if the version in npm is the latest with the fix for authentication but I still receive this error.

**Comment by lsiddiquee** [comment]
Apologies for the late response. For some reason I did not get any notification, and also have been super busy hence did not have time to come back to the repo. I will look into it soon. Will update as soon as I have any.

**Comment by lsiddiquee** [comment]
@kitzler-walli new version pushed. Please test.

**Comment by lsiddiquee** [comment]
This issue is now fixed.
