### ISSUE TITLE
Has the api stopped working ?

### ISSUE THREAD

**Issue by hemang249** [lsiddiquee/bmw-connected-drive#6]
I was using the API for my BMW and today my tokens stopped refreshing and i got this back as a response:

```
{
  error: 'client disabled',
  error_description: 'provided clients are disabled'
}
```
Status Code: 401

Is it just on my end or are you experiencing this as well?

**Comment by lsiddiquee** [comment]
Can you try again? I am using this library on Homey for integration and it was not working yesterday and i was getting some other error but it started working again today.

**Comment by hemang249** [comment]
Yeah i tried again, same thing.  Seems they blocked the API Key.

**Comment by lsiddiquee** [comment]
Yes it is broken again. Will update once i found the correct key.
